### ISSUE TITLE
Some couriers show "Invalid Date" for Expected

### ISSUE THREAD

**Issue by tedcook94** [tborychowski/courier#2]
All of my shipments from FedEx show "Invalid Date" for the Expected field. I suspect that this has something to do with the time being included ("T00:00:00") in the "expected_delivery" field.

![Capture](https://user-images.githubusercontent.com/33679293/120891852-6dbe7580-c5d0-11eb-8b20-bb6af7ba7c6f.PNG)

**Comment by tborychowski** [comment]
please check the latest version (v0.0.9) and reopen if this is still an issue.

**Comment by tedcook94** [comment]
That fixed it. Thanks!
