### ISSUE TITLE
Multi-arch image on Docker Hub

### ISSUE THREAD

**Issue by axeleroy** [tborychowski/courier#3]
Hello,

The image on Docker Hub only supports `amd64` when the base image (`alpine`) also supports `arm/v6` and `arm/v7`, which would allow users to user courier on Raspberry Pies and similar ARM-based SBCs.

See
* [Leverage multi-CPU architecture support](https://docs.docker.com/desktop/multi-arch/#build-multi-arch-images-with-buildx) (docs.docker.com)
* [Multi-arch build and images, the simple way](https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/) (docker.com/blog)

**Comment by tborychowski** [comment]
I appreciate your help, but I don't have enough time these days, to devote to this project.
(I switched to a mac app "Parcel", which does this and much more, and it's frictionless comparing to this elaborate complication).

**Comment by tborychowski** [comment]
I will have a look.

**Comment by tborychowski** [comment]
it was extremely easy.
`v0.0.11` and `latest` are multi-arch now.
Thanks!

**Comment by axeleroy** [comment]
Cool, it work, thanks!
